# Generated by Django 3.0.2 on 2020-01-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_zero_four_eight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_follower',
            field=models.IntegerField(default=0, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='user',
            name='num_following',
            field=models.IntegerField(default=0, verbose_name='Followings'),
        ),
    ]
