# Generated by Django 3.0.2 on 2020-01-19 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('two_zero_four_eight', '0005_auto_20200119_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration_second',
            field=models.PositiveIntegerField(verbose_name='Duration in Second'),
        ),
        migrations.AlterField(
            model_name='game',
            name='move',
            field=models.PositiveIntegerField(verbose_name='Number of Moves'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.PositiveIntegerField(default=1, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_2048_second',
            field=models.PositiveIntegerField(verbose_name='Time taken to achieve 2048'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fastest_solve',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fastest Solve'),
        ),
        migrations.AlterField(
            model_name='user',
            name='highest_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Highest Score'),
        ),
        migrations.AlterIndexTogether(
            name='follow',
            index_together={('user', 'follower')},
        ),
    ]
