# Generated by Django 3.0.2 on 2020-01-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_zero_four_eight', '0006_auto_20200119_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_played',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Games Played'),
        ),
    ]
