# Generated by Django 3.0.2 on 2020-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_zero_four_eight', '0008_auto_20200120_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='useless_move',
            field=models.IntegerField(default=0, verbose_name='Number of useless moves'),
        ),
        migrations.AlterField(
            model_name='game',
            name='move',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Moves'),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_played',
            field=models.IntegerField(default=0, verbose_name='Number of Games Played'),
        ),
    ]
