# Generated by Django 3.0.2 on 2020-01-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_zero_four_eight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
