# Generated by Django 3.0.2 on 2020-01-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_zero_four_eight', '0003_auto_20200119_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vip_level',
        ),
    ]
