# Generated by Django 3.0.2 on 2020-01-20 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('two_zero_four_eight', '0007_auto_20200120_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_2048_second',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time taken to achieve 2048'),
        ),
    ]
